#!/bin/ash
/bin/busybox mkdir -p /usr/bin /usr/sbin /proc /sys /dev /tmp/run
/bin/busybox --install -s
export PATH=/usr/bin:/bin:/usr/sbin:/sbin

for d in 1 2 3 4 5 6; do
  mknod /dev/tty$d c 4 $d
done

[ -c /dev/null ] || mknod -m 666 /dev/null c 1 3

mount -t proc -o noexec,nosuid,nodev proc /proc
mount -t sysfs -o noexec,nosuid,nodev sysfs /sys
mount -t devtmpfs -o exec,nosuid,mode=0755,size=2M devtmpfs /dev 2>/dev/null \
	|| mount -t tmpfs -o exec,nosuid,mode=0755,size=2M tmpfs /dev

# pty device nodes (later system will need it)
[ -c /dev/ptmx ] || mknod -m 666 /dev/ptmx c 5 2
[ -d /dev/pts ] || mkdir -m 755 /dev/pts
mount -t devpts -o gid=5,mode=0620,noexec,nosuid devpts /dev/pts

# shared memory area (later system will need it)
[ -d /dev/shm ] || mkdir /dev/shm
mount -t tmpfs -o nodev,nosuid,noexec shm /dev/shm

exec /bin/busybox sh
