#!/bin/sh

set -e

echo "Partition /dev/sda..."
echo -e "o\nn\np\n1\n\n\na\n1\nw" | fdisk /dev/sda

echo "Format /dev/sda1..."

mkfs.ext4 /dev/sda1

mkdir /run/disk
mount -t ext4 /dev/sda1 /run/disk

mkdir -p /run/disk/terra
tar -C /run/disk/terra -zxf /run/iso/os.tgz
mv /run/disk/terra/boot /run/disk/

mount --bind /run/disk/boot /boot

grub-install /dev/sda

grub-mkconfig -o /boot/grub/grub.cfg

umount /boot
umount /run/disk

echo "Reboot and enjoy..."
