#!/bin/sh

mkdir -p /run/sshd
/usr/sbin/sshd -h /etc/ssh/ssh_host_rsa_key &

ip link set lo up

echo "setting up dhcp..."
sleep 1
dhclient || true

rm /dev/console
ln -s /dev/ttyS0 /dev/console

ip -f inet a

exec /bin/sh
