// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/stellarproject/terraos/api/v1/services/infrastructure.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	types1 "github.com/gogo/protobuf/types"
	types "github.com/stellarproject/terraos/api/v1/types"
	grpc "google.golang.org/grpc"
	io "io"
	math "math"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ProvisionNodeRequest struct {
	Hostname             string             `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Mac                  string             `protobuf:"bytes,2,opt,name=mac,proto3" json:"mac,omitempty"`
	Image                string             `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	FsSize               int64              `protobuf:"varint,4,opt,name=fs_size,json=fsSize,proto3" json:"fs_size,omitempty"`
	Subvolumes           []*types.Subvolume `protobuf:"bytes,5,rep,name=subvolumes,proto3" json:"subvolumes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ProvisionNodeRequest) Reset()      { *m = ProvisionNodeRequest{} }
func (*ProvisionNodeRequest) ProtoMessage() {}
func (*ProvisionNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a5ce8b13a97981, []int{0}
}
func (m *ProvisionNodeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProvisionNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProvisionNodeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProvisionNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionNodeRequest.Merge(m, src)
}
func (m *ProvisionNodeRequest) XXX_Size() int {
	return m.Size()
}
func (m *ProvisionNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionNodeRequest proto.InternalMessageInfo

type ProvisionNodeResponse struct {
	Node                 *types.Node `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ProvisionNodeResponse) Reset()      { *m = ProvisionNodeResponse{} }
func (*ProvisionNodeResponse) ProtoMessage() {}
func (*ProvisionNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a5ce8b13a97981, []int{1}
}
func (m *ProvisionNodeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProvisionNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProvisionNodeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProvisionNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProvisionNodeResponse.Merge(m, src)
}
func (m *ProvisionNodeResponse) XXX_Size() int {
	return m.Size()
}
func (m *ProvisionNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProvisionNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProvisionNodeResponse proto.InternalMessageInfo

type ListNodeResponse struct {
	Nodes                []*types.Node `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ListNodeResponse) Reset()      { *m = ListNodeResponse{} }
func (*ListNodeResponse) ProtoMessage() {}
func (*ListNodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a5ce8b13a97981, []int{2}
}
func (m *ListNodeResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListNodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListNodeResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListNodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNodeResponse.Merge(m, src)
}
func (m *ListNodeResponse) XXX_Size() int {
	return m.Size()
}
func (m *ListNodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListNodeResponse proto.InternalMessageInfo

type InstallPXERequest struct {
	Image                string   `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InstallPXERequest) Reset()      { *m = InstallPXERequest{} }
func (*InstallPXERequest) ProtoMessage() {}
func (*InstallPXERequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a5ce8b13a97981, []int{3}
}
func (m *InstallPXERequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InstallPXERequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InstallPXERequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InstallPXERequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstallPXERequest.Merge(m, src)
}
func (m *InstallPXERequest) XXX_Size() int {
	return m.Size()
}
func (m *InstallPXERequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InstallPXERequest.DiscardUnknown(m)
}

var xxx_messageInfo_InstallPXERequest proto.InternalMessageInfo

type DeleteNodeRequest struct {
	Hostname             string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteNodeRequest) Reset()      { *m = DeleteNodeRequest{} }
func (*DeleteNodeRequest) ProtoMessage() {}
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a5ce8b13a97981, []int{4}
}
func (m *DeleteNodeRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeleteNodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeleteNodeRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeleteNodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteNodeRequest.Merge(m, src)
}
func (m *DeleteNodeRequest) XXX_Size() int {
	return m.Size()
}
func (m *DeleteNodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteNodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteNodeRequest proto.InternalMessageInfo

type InfoResponse struct {
	PxeVersion           string          `protobuf:"bytes,1,opt,name=pxe_version,json=pxeVersion,proto3" json:"pxe_version,omitempty"`
	Gateway              string          `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Targets              []*types.Target `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *InfoResponse) Reset()      { *m = InfoResponse{} }
func (*InfoResponse) ProtoMessage() {}
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1a5ce8b13a97981, []int{5}
}
func (m *InfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *InfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_InfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *InfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoResponse.Merge(m, src)
}
func (m *InfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *InfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InfoResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ProvisionNodeRequest)(nil), "io.stellarproject.services.v1.ProvisionNodeRequest")
	proto.RegisterType((*ProvisionNodeResponse)(nil), "io.stellarproject.services.v1.ProvisionNodeResponse")
	proto.RegisterType((*ListNodeResponse)(nil), "io.stellarproject.services.v1.ListNodeResponse")
	proto.RegisterType((*InstallPXERequest)(nil), "io.stellarproject.services.v1.InstallPXERequest")
	proto.RegisterType((*DeleteNodeRequest)(nil), "io.stellarproject.services.v1.DeleteNodeRequest")
	proto.RegisterType((*InfoResponse)(nil), "io.stellarproject.services.v1.InfoResponse")
}

func init() {
	proto.RegisterFile("github.com/stellarproject/terraos/api/v1/services/infrastructure.proto", fileDescriptor_c1a5ce8b13a97981)
}

var fileDescriptor_c1a5ce8b13a97981 = []byte{
	// 561 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0x71, 0x3e, 0xe8, 0x04, 0xa1, 0x76, 0x15, 0xc0, 0x32, 0xc2, 0x44, 0x96, 0x90, 0x82,
	0x90, 0xd6, 0x24, 0xad, 0x38, 0x14, 0x4e, 0x88, 0x20, 0x85, 0xcf, 0xca, 0xad, 0xaa, 0x8a, 0x4b,
	0xe5, 0xa4, 0x13, 0xd7, 0xc8, 0xf6, 0x9a, 0xdd, 0xb5, 0x69, 0x7a, 0xe2, 0xc6, 0x7f, 0xe2, 0x17,
	0xf4, 0x88, 0x38, 0x71, 0xa4, 0xf9, 0x25, 0xc8, 0x76, 0x9c, 0x36, 0x84, 0x24, 0xed, 0xc5, 0xda,
	0xd9, 0x9d, 0x37, 0x7a, 0xfb, 0xde, 0x5b, 0xc3, 0x6b, 0xd7, 0x93, 0xc7, 0x71, 0x9f, 0x0e, 0x58,
	0x60, 0x09, 0x89, 0xbe, 0xef, 0xf0, 0x88, 0xb3, 0xcf, 0x38, 0x90, 0x96, 0x44, 0xce, 0x1d, 0x26,
	0x2c, 0x27, 0xf2, 0xac, 0xa4, 0x6d, 0x09, 0xe4, 0x89, 0x37, 0x40, 0x61, 0x79, 0xe1, 0x90, 0x3b,
	0x42, 0xf2, 0x78, 0x20, 0x63, 0x8e, 0x34, 0xe2, 0x4c, 0x32, 0xf2, 0xc0, 0x63, 0x74, 0x16, 0x4f,
	0x0b, 0x00, 0x4d, 0xda, 0x7a, 0xc3, 0x65, 0x2e, 0xcb, 0x3a, 0xad, 0x74, 0x95, 0x83, 0xf4, 0xfb,
	0x2e, 0x63, 0xae, 0x8f, 0x56, 0x56, 0xf5, 0xe3, 0xa1, 0x85, 0x41, 0x24, 0x47, 0x93, 0xc3, 0xed,
	0x2b, 0x33, 0x93, 0xa3, 0x08, 0x45, 0xfe, 0xcd, 0xb1, 0xe6, 0x0f, 0x05, 0x1a, 0x3b, 0x9c, 0x25,
	0x9e, 0xf0, 0x58, 0xf8, 0x81, 0x1d, 0xa1, 0x8d, 0x5f, 0x62, 0x14, 0x92, 0xe8, 0x70, 0xf3, 0x98,
	0x09, 0x19, 0x3a, 0x01, 0x6a, 0x4a, 0x53, 0x69, 0xad, 0xd9, 0xd3, 0x9a, 0xac, 0x83, 0x1a, 0x38,
	0x03, 0xed, 0x46, 0xb6, 0x9d, 0x2e, 0x49, 0x03, 0x2a, 0x5e, 0xe0, 0xb8, 0xa8, 0xa9, 0xd9, 0x5e,
	0x5e, 0x90, 0x7b, 0x50, 0x1b, 0x8a, 0x43, 0xe1, 0x9d, 0xa2, 0x56, 0x6e, 0x2a, 0x2d, 0xd5, 0xae,
	0x0e, 0xc5, 0xae, 0x77, 0x8a, 0xa4, 0x0b, 0x20, 0xe2, 0x7e, 0xc2, 0xfc, 0x38, 0x40, 0xa1, 0x55,
	0x9a, 0x6a, 0xab, 0xde, 0x79, 0x44, 0xe7, 0x85, 0xc9, 0x99, 0x26, 0x6d, 0xba, 0x5b, 0x74, 0xdb,
	0x97, 0x80, 0xe6, 0x7b, 0xb8, 0xf3, 0x0f, 0x77, 0x11, 0xb1, 0x50, 0x20, 0xd9, 0x82, 0x72, 0xc8,
	0x8e, 0x72, 0xe2, 0xf5, 0x4e, 0x73, 0xd9, 0xe4, 0x0c, 0x97, 0x75, 0x9b, 0x6f, 0x60, 0xfd, 0x9d,
	0x27, 0xe4, 0xcc, 0xa4, 0x67, 0x50, 0x49, 0xcf, 0x84, 0xa6, 0x64, 0x24, 0x57, 0x8f, 0xca, 0xdb,
	0xcd, 0xc7, 0xb0, 0xd1, 0x0b, 0x85, 0x74, 0x7c, 0x7f, 0xe7, 0xa0, 0x5b, 0x68, 0x3a, 0x55, 0x49,
	0xb9, 0xa4, 0x92, 0x69, 0xc1, 0xc6, 0x2b, 0xf4, 0x51, 0xe2, 0x15, 0xe5, 0x37, 0xbf, 0x2b, 0x70,
	0xab, 0x17, 0x0e, 0xd9, 0x94, 0xe4, 0x43, 0xa8, 0x47, 0x27, 0x78, 0x98, 0x20, 0x4f, 0x95, 0x98,
	0xf4, 0x43, 0x74, 0x82, 0xfb, 0xf9, 0x0e, 0xd1, 0xa0, 0xe6, 0x3a, 0x12, 0xbf, 0x3a, 0xa3, 0x89,
	0x69, 0x45, 0x49, 0x5e, 0x40, 0x4d, 0x3a, 0xdc, 0x45, 0x29, 0x34, 0x35, 0xbb, 0xa1, 0xb9, 0xec,
	0x86, 0x7b, 0x59, 0xab, 0x5d, 0x40, 0x3a, 0xbf, 0x54, 0xb8, 0xdd, 0x9b, 0x09, 0x39, 0x49, 0x60,
	0x6d, 0xea, 0x09, 0xd9, 0xa4, 0x4b, 0xc3, 0x4e, 0xff, 0x97, 0x3c, 0x7d, 0xeb, 0x7a, 0xa0, 0x89,
	0x06, 0x1f, 0xa1, 0x9c, 0x9a, 0x47, 0xee, 0xd2, 0xfc, 0xa9, 0xd0, 0xe2, 0xa9, 0xd0, 0x6e, 0xfa,
	0x54, 0x74, 0x6b, 0xc5, 0xd4, 0x39, 0xe7, 0xf7, 0x01, 0x2e, 0x1c, 0x24, 0x4f, 0x57, 0xc0, 0xe7,
	0xcc, 0xd6, 0x17, 0x10, 0x21, 0x36, 0x54, 0x73, 0xbb, 0x57, 0xce, 0x9c, 0x4b, 0xc5, 0xc2, 0x99,
	0x6f, 0xa1, 0x9c, 0x06, 0x62, 0xe1, 0xe5, 0x9f, 0xac, 0x64, 0x7f, 0x91, 0xa6, 0x97, 0x7b, 0x67,
	0xe7, 0x46, 0xe9, 0xf7, 0xb9, 0x51, 0xfa, 0x36, 0x36, 0x94, 0xb3, 0xb1, 0xa1, 0xfc, 0x1c, 0x1b,
	0xca, 0x9f, 0xb1, 0xa1, 0x7c, 0xda, 0xbe, 0xf6, 0x2f, 0xf0, 0x79, 0xb1, 0x38, 0x28, 0xf5, 0xab,
	0x19, 0xa9, 0xcd, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x85, 0x1e, 0x28, 0xa1, 0x49, 0x05, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InfrastructureClient is the client API for Infrastructure service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InfrastructureClient interface {
	Provision(ctx context.Context, in *ProvisionNodeRequest, opts ...grpc.CallOption) (*ProvisionNodeResponse, error)
	List(ctx context.Context, in *types1.Empty, opts ...grpc.CallOption) (*ListNodeResponse, error)
	InstallPXE(ctx context.Context, in *InstallPXERequest, opts ...grpc.CallOption) (*types1.Empty, error)
	Delete(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*types1.Empty, error)
	Info(ctx context.Context, in *types1.Empty, opts ...grpc.CallOption) (*InfoResponse, error)
}

type infrastructureClient struct {
	cc *grpc.ClientConn
}

func NewInfrastructureClient(cc *grpc.ClientConn) InfrastructureClient {
	return &infrastructureClient{cc}
}

func (c *infrastructureClient) Provision(ctx context.Context, in *ProvisionNodeRequest, opts ...grpc.CallOption) (*ProvisionNodeResponse, error) {
	out := new(ProvisionNodeResponse)
	err := c.cc.Invoke(ctx, "/io.stellarproject.services.v1.Infrastructure/Provision", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infrastructureClient) List(ctx context.Context, in *types1.Empty, opts ...grpc.CallOption) (*ListNodeResponse, error) {
	out := new(ListNodeResponse)
	err := c.cc.Invoke(ctx, "/io.stellarproject.services.v1.Infrastructure/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infrastructureClient) InstallPXE(ctx context.Context, in *InstallPXERequest, opts ...grpc.CallOption) (*types1.Empty, error) {
	out := new(types1.Empty)
	err := c.cc.Invoke(ctx, "/io.stellarproject.services.v1.Infrastructure/InstallPXE", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infrastructureClient) Delete(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*types1.Empty, error) {
	out := new(types1.Empty)
	err := c.cc.Invoke(ctx, "/io.stellarproject.services.v1.Infrastructure/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infrastructureClient) Info(ctx context.Context, in *types1.Empty, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/io.stellarproject.services.v1.Infrastructure/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InfrastructureServer is the server API for Infrastructure service.
type InfrastructureServer interface {
	Provision(context.Context, *ProvisionNodeRequest) (*ProvisionNodeResponse, error)
	List(context.Context, *types1.Empty) (*ListNodeResponse, error)
	InstallPXE(context.Context, *InstallPXERequest) (*types1.Empty, error)
	Delete(context.Context, *DeleteNodeRequest) (*types1.Empty, error)
	Info(context.Context, *types1.Empty) (*InfoResponse, error)
}

func RegisterInfrastructureServer(s *grpc.Server, srv InfrastructureServer) {
	s.RegisterService(&_Infrastructure_serviceDesc, srv)
}

func _Infrastructure_Provision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfrastructureServer).Provision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.services.v1.Infrastructure/Provision",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfrastructureServer).Provision(ctx, req.(*ProvisionNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Infrastructure_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfrastructureServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.services.v1.Infrastructure/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfrastructureServer).List(ctx, req.(*types1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Infrastructure_InstallPXE_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallPXERequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfrastructureServer).InstallPXE(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.services.v1.Infrastructure/InstallPXE",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfrastructureServer).InstallPXE(ctx, req.(*InstallPXERequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Infrastructure_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfrastructureServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.services.v1.Infrastructure/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfrastructureServer).Delete(ctx, req.(*DeleteNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Infrastructure_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfrastructureServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/io.stellarproject.services.v1.Infrastructure/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfrastructureServer).Info(ctx, req.(*types1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Infrastructure_serviceDesc = grpc.ServiceDesc{
	ServiceName: "io.stellarproject.services.v1.Infrastructure",
	HandlerType: (*InfrastructureServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Provision",
			Handler:    _Infrastructure_Provision_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Infrastructure_List_Handler,
		},
		{
			MethodName: "InstallPXE",
			Handler:    _Infrastructure_InstallPXE_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Infrastructure_Delete_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Infrastructure_Info_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/stellarproject/terraos/api/v1/services/infrastructure.proto",
}

func (m *ProvisionNodeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProvisionNodeRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Hostname) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintInfrastructure(dAtA, i, uint64(len(m.Hostname)))
		i += copy(dAtA[i:], m.Hostname)
	}
	if len(m.Mac) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintInfrastructure(dAtA, i, uint64(len(m.Mac)))
		i += copy(dAtA[i:], m.Mac)
	}
	if len(m.Image) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintInfrastructure(dAtA, i, uint64(len(m.Image)))
		i += copy(dAtA[i:], m.Image)
	}
	if m.FsSize != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintInfrastructure(dAtA, i, uint64(m.FsSize))
	}
	if len(m.Subvolumes) > 0 {
		for _, msg := range m.Subvolumes {
			dAtA[i] = 0x2a
			i++
			i = encodeVarintInfrastructure(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ProvisionNodeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProvisionNodeResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Node != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintInfrastructure(dAtA, i, uint64(m.Node.Size()))
		n1, err := m.Node.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ListNodeResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListNodeResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Nodes) > 0 {
		for _, msg := range m.Nodes {
			dAtA[i] = 0xa
			i++
			i = encodeVarintInfrastructure(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *InstallPXERequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InstallPXERequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Image) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintInfrastructure(dAtA, i, uint64(len(m.Image)))
		i += copy(dAtA[i:], m.Image)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *DeleteNodeRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeleteNodeRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Hostname) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintInfrastructure(dAtA, i, uint64(len(m.Hostname)))
		i += copy(dAtA[i:], m.Hostname)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *InfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *InfoResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.PxeVersion) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintInfrastructure(dAtA, i, uint64(len(m.PxeVersion)))
		i += copy(dAtA[i:], m.PxeVersion)
	}
	if len(m.Gateway) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintInfrastructure(dAtA, i, uint64(len(m.Gateway)))
		i += copy(dAtA[i:], m.Gateway)
	}
	if len(m.Targets) > 0 {
		for _, msg := range m.Targets {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintInfrastructure(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintInfrastructure(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *ProvisionNodeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Hostname)
	if l > 0 {
		n += 1 + l + sovInfrastructure(uint64(l))
	}
	l = len(m.Mac)
	if l > 0 {
		n += 1 + l + sovInfrastructure(uint64(l))
	}
	l = len(m.Image)
	if l > 0 {
		n += 1 + l + sovInfrastructure(uint64(l))
	}
	if m.FsSize != 0 {
		n += 1 + sovInfrastructure(uint64(m.FsSize))
	}
	if len(m.Subvolumes) > 0 {
		for _, e := range m.Subvolumes {
			l = e.Size()
			n += 1 + l + sovInfrastructure(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ProvisionNodeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Node != nil {
		l = m.Node.Size()
		n += 1 + l + sovInfrastructure(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ListNodeResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Nodes) > 0 {
		for _, e := range m.Nodes {
			l = e.Size()
			n += 1 + l + sovInfrastructure(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *InstallPXERequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Image)
	if l > 0 {
		n += 1 + l + sovInfrastructure(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *DeleteNodeRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Hostname)
	if l > 0 {
		n += 1 + l + sovInfrastructure(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *InfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PxeVersion)
	if l > 0 {
		n += 1 + l + sovInfrastructure(uint64(l))
	}
	l = len(m.Gateway)
	if l > 0 {
		n += 1 + l + sovInfrastructure(uint64(l))
	}
	if len(m.Targets) > 0 {
		for _, e := range m.Targets {
			l = e.Size()
			n += 1 + l + sovInfrastructure(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovInfrastructure(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozInfrastructure(x uint64) (n int) {
	return sovInfrastructure(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *ProvisionNodeRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ProvisionNodeRequest{`,
		`Hostname:` + fmt.Sprintf("%v", this.Hostname) + `,`,
		`Mac:` + fmt.Sprintf("%v", this.Mac) + `,`,
		`Image:` + fmt.Sprintf("%v", this.Image) + `,`,
		`FsSize:` + fmt.Sprintf("%v", this.FsSize) + `,`,
		`Subvolumes:` + strings.Replace(fmt.Sprintf("%v", this.Subvolumes), "Subvolume", "types.Subvolume", 1) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ProvisionNodeResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ProvisionNodeResponse{`,
		`Node:` + strings.Replace(fmt.Sprintf("%v", this.Node), "Node", "types.Node", 1) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ListNodeResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ListNodeResponse{`,
		`Nodes:` + strings.Replace(fmt.Sprintf("%v", this.Nodes), "Node", "types.Node", 1) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *InstallPXERequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&InstallPXERequest{`,
		`Image:` + fmt.Sprintf("%v", this.Image) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *DeleteNodeRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&DeleteNodeRequest{`,
		`Hostname:` + fmt.Sprintf("%v", this.Hostname) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func (this *InfoResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&InfoResponse{`,
		`PxeVersion:` + fmt.Sprintf("%v", this.PxeVersion) + `,`,
		`Gateway:` + fmt.Sprintf("%v", this.Gateway) + `,`,
		`Targets:` + strings.Replace(fmt.Sprintf("%v", this.Targets), "Target", "types.Target", 1) + `,`,
		`XXX_unrecognized:` + fmt.Sprintf("%v", this.XXX_unrecognized) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringInfrastructure(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *ProvisionNodeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInfrastructure
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProvisionNodeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProvisionNodeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hostname", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfrastructure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInfrastructure
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInfrastructure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hostname = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mac", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfrastructure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInfrastructure
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInfrastructure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mac = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Image", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfrastructure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInfrastructure
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInfrastructure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Image = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FsSize", wireType)
			}
			m.FsSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfrastructure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FsSize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Subvolumes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfrastructure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInfrastructure
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInfrastructure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Subvolumes = append(m.Subvolumes, &types.Subvolume{})
			if err := m.Subvolumes[len(m.Subvolumes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInfrastructure(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthInfrastructure
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthInfrastructure
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProvisionNodeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInfrastructure
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProvisionNodeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProvisionNodeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Node", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfrastructure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInfrastructure
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInfrastructure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Node == nil {
				m.Node = &types.Node{}
			}
			if err := m.Node.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInfrastructure(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthInfrastructure
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthInfrastructure
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListNodeResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInfrastructure
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListNodeResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListNodeResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nodes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfrastructure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInfrastructure
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInfrastructure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Nodes = append(m.Nodes, &types.Node{})
			if err := m.Nodes[len(m.Nodes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInfrastructure(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthInfrastructure
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthInfrastructure
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InstallPXERequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInfrastructure
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InstallPXERequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InstallPXERequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Image", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfrastructure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInfrastructure
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInfrastructure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Image = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInfrastructure(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthInfrastructure
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthInfrastructure
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeleteNodeRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInfrastructure
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeleteNodeRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeleteNodeRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hostname", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfrastructure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInfrastructure
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInfrastructure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hostname = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInfrastructure(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthInfrastructure
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthInfrastructure
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *InfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInfrastructure
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: InfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: InfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PxeVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfrastructure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInfrastructure
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInfrastructure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PxeVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Gateway", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfrastructure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInfrastructure
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthInfrastructure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Gateway = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Targets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInfrastructure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInfrastructure
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthInfrastructure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Targets = append(m.Targets, &types.Target{})
			if err := m.Targets[len(m.Targets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInfrastructure(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthInfrastructure
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthInfrastructure
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipInfrastructure(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowInfrastructure
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInfrastructure
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInfrastructure
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthInfrastructure
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthInfrastructure
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowInfrastructure
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipInfrastructure(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthInfrastructure
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthInfrastructure = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowInfrastructure   = fmt.Errorf("proto: integer overflow")
)
